<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle('Lowe\'s '. $this->translate('Admin Login'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/backend/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/backend/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/backend/css/signin.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/backend/js/bootstrap.min.js') ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>